<a href="https://colab.research.google.com/github/nirmal-ank/Transformers/blob/main/Next_Sentence_Prediction_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from transformers import BertForNextSentencePrediction, BertTokenizer
import torch

In [ ]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
bert_nsp = BertForNextSentencePrediction.from_pretrained('bert-base-uncased')

In [ ]:
bert_nsp

BertForNextSentencePrediction(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e

In [ ]:
text1 = "Software Engineering in the rise."
text2 = "There are many people transitioning to software engineering roles."

In [ ]:
inputs = tokenizer(text1, text2, return_tensors='pt')

In [ ]:
inputs

{'input_ids': tensor([[ 101, 4007, 3330, 1999, 1996, 4125, 1012,  102, 2045, 2024, 2116, 2111,
         6653, 2075, 2000, 4007, 3330, 4395, 1012,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [ ]:
inputs.input_ids

tensor([[ 101, 4007, 3330, 1999, 1996, 4125, 1012,  102, 2045, 2024, 2116, 2111,
         6653, 2075, 2000, 4007, 3330, 4395, 1012,  102]])

In [ ]:
inputs.token_type_ids

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
inputs.attention_mask

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
outputs = bert_nsp(**inputs)
outputs

NextSentencePredictorOutput(loss=None, logits=tensor([[ 6.3631, -6.3393]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [ ]:
outputs_labelled = bert_nsp(**inputs,labels=torch.LongTensor([0]))
outputs_labelled # 0 == next sentence and 1 == not next sentence

NextSentencePredictorOutput(loss=tensor(3.0994e-06, grad_fn=<NllLossBackward0>), logits=tensor([[ 6.3631, -6.3393]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [ ]:
outputs_labelled = bert_nsp(**inputs,labels=torch.LongTensor([1]))
outputs_labelled # 0 == next sentence and 1 == not next sentence; Very high loss means not 1

NextSentencePredictorOutput(loss=tensor(12.7024, grad_fn=<NllLossBackward0>), logits=tensor([[ 6.3631, -6.3393]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)